mailgunevent_list:
    path: /mailgun/events/{page}/{pageSize}
    defaults:
        _controller: 'Azine\MailgunWebhooksBundle\Controller\MailgunController::eventIndexAction'
        page: 1
        pageSize: 25

mailgunevent_show:
    path: /mailgun/event/{id}/show
    defaults:
        _controller: 'Azine\MailgunWebhooksBundle\Controller\MailgunController::eventShowAction'

mailgunevent_delete:
    path: /mailgun/event/delete/{eventId}
    defaults:
        _controller: 'Azine\MailgunWebhooksBundle\Controller\MailgunController::eventDeleteAction'

mailgunevent_delete_ajax:
    path: /mailgun/event/delete
    defaults:
        _controller: 'Azine\MailgunWebhooksBundle\Controller\MailgunController::eventDeleteAction'

mailgun_message_summary:
    path: /mailgun/messages/show/{id}
    defaults:
        _controller: 'Azine\MailgunWebhooksBundle\Controller\MailgunController::messageSummaryShowAction'

mailgun_message_summary_list:
    path: /mailgun/messages/{page}/{pageSize}
    defaults:
        _controller: 'Azine\MailgunWebhooksBundle\Controller\MailgunController::messageSummaryIndexAction'
        page: 1
        pageSize: 25

mailgun_overview:
    path: /mailgun/
    defaults:
        _controller: 'Azine\MailgunWebhooksBundle\Controller\MailgunController::eventOverviewAction'
