parameters:

services:
    azine_mailgun.service:
        class: Azine\MailgunWebhooksBundle\Services\AzineMailgunService
        arguments: ["@doctrine"]

    azine.mailgun.webhooks.bundle.twig.filters:
        class: Azine\MailgunWebhooksBundle\Services\AzineMailgunTwigExtension
        public: false
        tags:
            - { name: twig.extension }

    azine.mailgun.webhooks.event_listener.created:
        class: Azine\MailgunWebhooksBundle\EventListener\EventCreatedListener
        tags: 
            - { name: kernel.event_listener, event: azine.mailgun.webhooks.event.create, method: onEventCreated}
        arguments:
            - '@azine.mailgun.mailer'
            - '%azine_mailgun_webhooks_spam_alerts_enabled%'
            
    azine.mailgun.mailer: 
        class: Azine\MailgunWebhooksBundle\Services\AzineMailgunMailerService
        arguments:
            - '@mailer'
            - '@twig'
            - '@translator'
            - '%mailer_user%'
            - '%azine_mailgun_webhooks_spam_alerts_ticket_id%'
            - '%azine_mailgun_webhooks_spam_alerts_ticket_subject%'
            - '%azine_mailgun_webhooks_spam_alerts_ticket_message%'
            - '%azine_mailgun_webhooks_spam_alerts_alerts_recipient_email%'
            - '@doctrine.orm.entity_manager'
            - '%azine_mailgun_webhooks_spam_alerts_interval%'