parameters:

services:
    azine_mailgun.service:
        class: Azine\MailgunWebhooksBundle\Services\AzineMailgunService
        arguments: ["@doctrine"]
        public: true
        
    azine_mailgun.cockpit_service:
        class: Azine\MailgunWebhooksBundle\Services\AzineMailgunCockpitService
        arguments: 
            - '@doctrine'
            - '@twig'
            - '%azine_mailgun_webhooks_email_domain%'

    azine.mailgun.webhooks.bundle.twig.filters:
        class: Azine\MailgunWebhooksBundle\Services\AzineMailgunTwigExtension
        public: false
        tags:
            - { name: twig.extension }

    azine.command.delete_old_entries:
        class: Azine\MailgunWebhooksBundle\Command\DeleteOldEntriesCommand
        arguments:
            - '@azine_mailgun.service'
        tags:
            - { name: console.command, command: mailgun:delete-events }

    azine.mailgun.webhooks.event_listener.created:
        class: Azine\MailgunWebhooksBundle\EventListener\EventCreatedListener
        tags: 
            - { name: kernel.event_listener, event: azine.mailgun.webhooks.event.create, method: onEventCreated}
        arguments:
            - '@azine.mailgun.mailer'
            - '%azine_mailgun_webhooks_spam_alerts_enabled%'
            
    azine.mailgun.mailer: 
        class: Azine\MailgunWebhooksBundle\Services\AzineMailgunMailerService
        arguments:
            - '@mailer'
            - '@twig'
            - '@translator'
            - '%mailer_user%'
            - '%azine_mailgun_webhooks_spam_alerts_ticket_id%'
            - '%azine_mailgun_webhooks_spam_alerts_ticket_subject%'
            - '%azine_mailgun_webhooks_spam_alerts_ticket_message%'
            - '%azine_mailgun_webhooks_spam_alerts_alerts_recipient_email%'
            - '@doctrine'
            - '%azine_mailgun_webhooks_spam_alerts_interval%'

    azine.mailgun.hetrixtools.service:
        class: Azine\MailgunWebhooksBundle\Services\HetrixtoolsService\AzineMailgunHetrixtoolsService
        arguments:
            - '@logger'
            - '%azine_mailgun_webhooks_hetrixtools_service_api_key%'
            - '%azine_mailgun_webhooks_hetrixtools_service_blacklist_check_ip_url%'

    azine.mailgun.check_ip_address_is_blacklised.command:
        class: Azine\MailgunWebhooksBundle\Command\CheckIpAddressIsBlacklistedCommand
        arguments:
            - '@doctrine'
            - '@azine.mailgun.hetrixtools.service'
            - '@azine.mailgun.mailer'
            - '%kernel.environment%'
        tags:
            - { name: console.command }

    Azine\MailgunWebhooksBundle\Controller\MailgunEventController:
        calls:
            - [setContainer, ["@service_container"]]

    Azine\MailgunWebhooksBundle\Controller\MailgunController:
        calls:
            - [setContainer, ["@service_container"]]


