parameters:

services:
    azine_mailgun.service:
        class: Azine\MailgunWebhooksBundle\Services\AzineMailgunService
        arguments: ["@doctrine"]

    azine.mailgun.webhooks.bundle.twig.filters:
        class: Azine\MailgunWebhooksBundle\Services\AzineMailgunTwigExtension
        public: false
        tags:
            - { name: twig.extension }
