parameters:

services:
    azine_mailgun.service:
        class: Azine\MailgunWebhooksBundle\Services\AzineMailgunService
        arguments: ["@doctrine"]
        public: true
        
    azine_mailgun.cockpit_service:
        class: Azine\MailgunWebhooksBundle\Services\AzineMailgunCockpitService
        arguments: 
            - '@doctrine'
            - '@twig'
            - '%azine_mailgun_webhooks_email_domain%'

    azine.mailgun.webhooks.bundle.twig.filters:
        class: Azine\MailgunWebhooksBundle\Services\AzineMailgunTwigExtension
        public: false
        tags:
            - { name: twig.extension }
        
    azine.command.delete_old_entries:
        class: Azine\MailgunWebhooksBundle\Command\DeleteOldEntriesCommand
        tags:
            - { name: console.command }
