# default-configurations
imports:
    - javascript
    - php   
    
tools:
    external_code_coverage:
        timeout: 1200 # Timeout 20min in seconds.
        
    php_pdepend:
        excluded_dirs:
          - Entity

    php_cs_fixer: true
        
        