<?php

namespace Azine\MailgunWebhooksBundle\Entity\Repositories;

/**
 * HetrixToolsBlacklistResponseNotificationRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HetrixToolsBlacklistResponseNotificationRepository extends \Doctrine\ORM\EntityRepository
{
}
