<?php

namespace Azine\MailgunWebhooksBundle\Entity\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * MailgunAttachmentRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailgunAttachmentRepository extends EntityRepository
{
}
