<?php

namespace Azine\MailgunWebhooksBundle\Entity\Repositories;

use Azine\MailgunWebhooksBundle\Entity\EmailTrafficStatistics;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\EntityRepository;

/**
 * EmailTrafficStatisticsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailTrafficStatisticsRepository extends EntityRepository
{
    /**
     * Get last EmailTrafficStatistics by action
     * @param $action
     *
     * @return EmailTrafficStatistics
     */
    public function getLastByAction($action)
    {
        $q = $this->getEntityManager()->createQueryBuilder()
            ->select('e')
            ->from($this->getEntityName(), "e")
            ->where('e.action = :action')
            ->orderBy('e.created ', 'desc')
            ->setParameters(['action' => $action]);

        try {

            return $q->getQuery()->getSingleResult();
        }
        catch(\Doctrine\ORM\NoResultException $e) {

            return null;
        }
    }
}