<?php

namespace Azine\MailgunWebhooksBundle\Entity\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * MailgunEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailgunEventRepository extends EntityRepository{
}
